### PR TITLE
Use proper HUBOT_ namespacing for Resumator ENV vars

### PR DESCRIPTION
**Pull request by fromonesrc**
Better follows the convention of `HUBOT_` prefixing on ENV vars

### CODE REVIEW

**Comment by technicalpickles** [comment]
I've been merging stuff despite #1113, but not going to do this one since it'll break backwards compatibility.

**Comment by ChrisMissal** [comment]
@technicalpickles Do you think it's safe to just create a new version and publish on npm? The users of the old script will not have obtained it through npm and it could then be versioned like normal.

Sorry, I haven't really kept up with all the hubot-scripts changes and moves over the past couple years.

**Comment by technicalpickles** [comment]
@ChrisMissal I just released 2.16.2, thanks for the reminder :sparkles:

**Comment by ChrisMissal** [comment]
Sure thing :smile:

I just ran across this issue and was curious if there was anything I could do to help (fix/improve/etc) with the resumator.coffee script since I created it.

**Comment by technicalpickles** [comment]
@ChrisMissal well since you asked :grin: ... we are trying to get folks to extract scripts out of this repository and moved into their own. See https://github.com/github/hubot-scripts/issues/1641 and https://github.com/github/hubot-scripts/issues/1113 for background. If you do want to extract resumator, just let us know over on #1641 when it's been released :sparkles:

**Comment by ChrisMissal** [comment]
@technicalpickles Done :+1:

**Pull request closed without merging**
