### PR TITLE
updated to use new memecaptain API

### PR DESCRIPTION
**Pull request by ericjsilva**
Memecaptain.com recently deprecated their old API causing this script to no longer work. Updated script to use new API with polling logic.

Also added a few common/popular meme images.

### CODE REVIEW

**Comment by tannermares** [comment]
:+1:

**Comment by mmb** [comment]
:+1:

**Comment by spockNinja** [comment]
:+1:

**Comment by mr337** [comment]
zomg where my memes be? :+1:

**Comment by technicalpickles** [comment]
We're in the process of deprecating this repository in favor of separate repositories per script over in #1641 . I can merge this now to get functionality out there, but it'd be better if this was extracted and released as a separate repository.

Actually, this has already been extracted to https://github.com/cycomachead/hubot-meme so that'd be a better script to use. @ericjsilva I'd check that out, and make the changes there too if they are applicable.

**Comment by technicalpickles** [comment]
Released in 2.16.2, thanks! cc https://github.com/github/hubot-scripts/pull/1660

**Pull request merged**
