### PR TITLE
Add ids to hubot scripts to control what rooms they can run in

### PR DESCRIPTION
**Pull request by wsoula**
I am about to leave on vacation for three weeks, where I probably won't work on this so I thought I would submit where I got in adding ids to all the scripts.

### CODE REVIEW

**Comment by michaelansel** [comment]
:scream: This is awesome work! I'll try to get it reviewed before you get back :grin:

**Comment by wsoula** [comment]
Thanks, I forgot to mention this addresses issue #1663

**Comment by technicalpickles** [comment]
One thing I brought up in https://github.com/hubot-scripts/hubot-pager-me/pull/54 that is cause for concern when adding IDs:

> how does this affect users that aren't up on hubot 2.13.0 yet?
>
> Maybe could do something like check robot.respond.length, and fail it isn't 3? (It used to be 2 before options).

**Comment by michaelansel** [comment]
Can/should we bump hubot-scripts to require hubot >= 2.13? Haven't thought through the implications yet...

**Comment by wsoula** [comment]
@technicalpickles when you say fail if it isn't 3, do you mean these scripts should fail gracefully putting out an unsupported hubot version error message, instead of whatever error would be spit out right now?  I could put that in, but probably won't be able to before vacation.  What are your thoughts on making hubot-scripts require hubot >= 2.13.0 like @michaelansel suggested?

**Comment by technicalpickles** [comment]
> when you say fail if it isn't 3, do you mean these scripts should fail gracefully putting out an unsupported hubot version error message, instead of whatever error would be spit out right now

I mean hubot should fail outright if trying to load this with an older version. Without that and the function signature changing, I think the user would get a pretty confusing error like "Object is not a function", since now it's getting an object hash instead of a function.

I haven't thought of a graceful way to support both that doesn't involve a lot of extra code. I don't think there's a graceful way to support both, so it would require 2.13.0. In general, I prefer hubot failing during boot this rather than "gracefully" not loading the scripts, because a hubot user would expect those scripts to be present, and they won't be if they are skipped.

**Comment by technicalpickles** [comment]
This repository is deprecated, so we won't be updating all these packages with ids.

**Pull request closed without merging**
